---
deployment:
  tasks:
    - export DEPLOYPATH=/home/linkewjr/public_html/cashflow/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp config.php $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH